### ISSUE TITLE
Plugin Clean Up Request...

### ISSUE THREAD

**Issue by vanndigitalnetworks** [dolatabadi/cleanup-wp-plugins#3]
...for:

WordPress Popular Posts https://wordpress.org/plugins/wordpress-popular-posts/

**Comment by frankshrum** [comment]
Let's add LeadMagic to the list. I've deleted their advert then change the page and it's back. It says:

LeadMagic provides integration with RegistrationMagic as well. You can install it from Here.

**Comment by dolatabadi** [comment]
@frankshrum do you have the plugin's url and a screenshot of the ad?
I will release an update soon to include several other plugins, will include that one too.
